DemoWebSite/config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'homes#top'
  get 'home/about' => 'homes#about'
  get 'home/thanks' => 'homes#thanks'

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :update, :edit, :create, :destroy]
    resources :items, only: [:index, :new, :show, :edit, :update, :destroy, :create]
    resources :orders, only: [:index, :show, :update, :edit]
    resources :order_details, only: [:show, :update]
  end

  scope module: :public do
    resources :customers, only: [:index, :show, :edit, :update, :create]
    resources :items, only: [:index, :show]
    resources :orders, only: [:index, :show, :new, :create, :update, :destroy] do
      collection do
        post 'confirm'
        get 'confirm'
      end
    end
    resources :order_details, only: [:show]
    resources :cart_items, only: [:index, :show, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :send_addresses, only: [:index, :edit, :destroy, :create, :update]
  end


end

DemoWebSite/app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :send_addresses, dependent: :destroy
end

DemoWebSite/app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).per(8)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to edit_customer_path(@customer.id)
    else
      render :edit
    end
  end
  
  private
  
  def customer_params
    params.require(:cusotomer).permit(:last_name,:first_name,:kana_last_name,:kana_first_name,:postal_code,:address,:telephone,:email,:is_deleted)
  end
end

DemoWebSite/app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

DemoWebSite/app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

DemoWebSite/app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

DemoWebSite/app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

DemoWebSite/app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

DemoWebSite/app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

DemoWebSite/app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

DemoWebSite/app/helpers/customers_helper.rb
module CustomersHelper
end

DemoWebSite/app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <nav class="navbar navbar-light">
        <h2 class='title'>Editing <%= @customer.last_name %><%= @customer.first_name %>'s data</h2>
      </nav>
    </div>
  </div>
  <%= render partial: 'layouts/flash' %>
  <div class='row'>
    <div class='mx-auto'>
      <%= form_for(@customer, url: admin_path(@customer)) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <table class="table table-borderless newitem title">
          <tr>
            <td><lebel>Customer_ID</lebel></td>
            <td><%= @customer.id %></td>
          </tr>
          <div class="form-group">
            <tr>
              <td><lebel>Name</lebel></td>
              <td><%= f.text_field :last_name,class:"form-control"  %></td>
              <td><%= f.text_field :first_name,class:"form-control"  %></td>
            </tr>
          </div>
          <div class="form-group">
            <tr>
              <td><lebel>Kana</lebel></td>
              <td><%= f.text_field :last_name_kana,class:"form-control" %></td>
              <td><%= f.text_field :first_name_kana,class:"form-control"  %></td>
            </tr>
          </div>
          <div class="form-group">
            <tr>
              <td><lebel>Postal Code</lebel></td>
              <td><%= f.text_field :postal_code, class:"form-control"  %></td>
            </tr>
          </div>
          <div class="form-group">
            <tr>
               <td><lebel>Address</lebel></td>
               <td colspan="2"><%= f.text_field :address,class:"form-control" %></td>
            </tr>
          </div>
          <div class="form-group">
            <tr>
               <td><lebel>Phone Number</lebel></td>
               <td><%= f.telephone_field :telephone_number,class:"form-control"  %></td>
            </tr>
          </div>
          <div class="form-group">
            <tr>
               <td><lebel>email</lebel></td>
               <td><%= f.email_field :email,class:"form-control"  %></td>
            </tr>
          </div>
          <div class='form-group'>
            <tr>
               <td><label>Status</label></td>
               <td>
                  <%= f.radio_button :id_deleted, :false %>
                  <%= f.label :id_deleted, '有効', {value: :false, style: 'display: inline-block;'} %>
                  <%= f.radio_button :id_deleted, :true %>
                  <%= f.label :id_deleted, '退会', {value: :true, style: 'display: inline-block;'} %>
               </td>
            </tr>
          </div>
        </table>
        <div class="form-group hoge title">
          <%= f.submit "Submit", class:'btn btn-lg btn-dark' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

DemoWebSite/app/views/admin/customers/index.html.erb
 <div class="container">
   <div class="row">
      <div class="col-md-3 offset-md-1">
        <nav class="navbar navbar-light">
         <h2>Customers</h2>
         </nav>
      </div>
   </div>
   <div class="row center">
       <div class="col-8 ">
          <table class='table'>
              <thead class="thead-light bodydesign">
                 <tr>
                    <th class='text-white bg-dark'>Customer_ID</th>
                    <th class='text-white bg-dark'>Name</th>
                    <th class='text-white bg-dark'>email</th>
                    <th class='text-white bg-dark'>Status</th>
                 </tr>
              </thead>
              <tbody class='title bodydesign'>
                <% @customers.each do |customer| %>
                 <tr>
                    <td><%= customer.id %></td>
                    <td><%= link_to admin_customer_path(customer), :style => 'color:black;'  do %>
                         <%= customer.last_name %><%= customer.first_name %>
                     <% end %>
                    </td>
                    <td><%= customer.email %></td>
                      <% if customer.is_deleted == true %>
                        <th><span>退会</span></th>
                      <% else %>
                        <th><font color="#008000">有効</font></th>
                      <% end %>
                   </tr>
                  <% end %>
               </tbody>
          </table>
      <div class='p-top__paginate pagination-design'><%= paginate(@customers) %></div>
        </diV>
     </div>
  </div>

DemoWebSite/app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <nav class="navbar navbar-light">
        <h2 class='title'>Detail of <%= @customer.last_name %><%= @customer.first_name %></h2>
      </nav>
    </div>
  </div>
  <%= render partial: 'layouts/flash' %>
  <div class='row'>
    <div class='mx-auto'>
      <table class="table table-borderless">
        <tr>
          <td><lebel>Customer_ID</lebel></td>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <td><label>Name</label></td>
          <td><%= @customer.last_name %><%= @customer.first_name %></td>
        </tr>
        <tr>
          <td><lebel>Kana</lebel></td>
          <td><%= @customer.kana_last_name %><%= @customer.kana_first_name %></td>
        </tr>
        <tr>
          <td><lebel>Postal Code</lebel></td>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <td><lebel>Address</lebel></td>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <td><lebel>Phone Number</lebel></td>
          <td><%= @customer.telephone %></td>
        </tr>
        <tr>
          <td><lebel>email</lebel></td>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <td>
           <lebel>Status</lebel>
          </td>
          <td>
            <% if @customer.is_deleted == true %>
              退会
            <% else %>
              <font color="#008000">有効</font>
            <% end %>
          </td>
        </tr>
         <td><%= link_to "Edit", edit_admin_customer_path(@customer.id), class: "btn btn-dark" %></td>
         <td><%= link_to "Order List",admin_orders_path,class:"btn btn-secondary" %></td>
      </table>
    </div>
  </div>
</div>