DemoWebSite/config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'homes#top'
  get 'home/about' => 'homes#about'
  get 'home/thanks' => 'homes#thanks'

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :update, :edit, :create, :destroy]
    resources :items, only: [:index, :new, :show, :edit, :update, :destroy, :create]
    resources :orders, only: [:index, :show, :update, :edit]
    resources :order_details, only: [:show, :update]
  end

  scope module: :public do
    resources :customers, only: [:index, :show, :edit, :update, :create]
    resources :items, only: [:index, :show]
    resources :orders, only: [:index, :show, :new, :create, :update, :destroy] do
      collection do
        post 'confirm'
        get 'confirm'
      end
    end
    resources :order_details, only: [:show]
    resources :cart_items, only: [:index, :show, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :send_addresses, only: [:index, :edit, :destroy, :create, :update]
  end


end

DemoWebSite/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

DemoWebSite/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

DemoWebSite/app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
end

DemoWebSite/app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :send_addresses, dependent: :destroy
end

DemoWebSite/app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

DemoWebSite/app/models/item.rb
class Item < ApplicationRecord
    has_many :cart_items, dependent: :destroy
    has_many :order_details, dependent: :destroy
    belongs_to :genre
    attachment :image
end

DemoWebSite/app/models/order.rb
class Order < ApplicationRecord
    has_many :order_details, dependent: :destroy
    belongs_to :customer

    attr_accessor :address_option
    attr_accessor :other_send_address

    enum payment_method: {
        'credit_card':0, 'bank_transfer':1
    }

    enum status: {
        '入金待ち':0, '入金確認':1, '製作中':2, '発送準備中':3, '発送済み':4
    }
end

DemoWebSite/app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
    
    enum making_status: {
        '着手不可':0, '製作待ち':1, '製作中':2, '製作完了':3
    }
end

DemoWebSite/app/models/send_address.rb
class SendAddress < ApplicationRecord
    belongs_to :customer
end

DemoWebSite/app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    @orders = Order.page(params[:page]).per(8)
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    #@order_detail = OrderDetail.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
      if @order.status == '入金確認'
        @order.order_details.each do |order_detail|
          order_detail.update(making_status: 1)
        end
      end
      redirect_to admin_order_path(@order)
  end

  private

  def order_params
    #params.permit(:customer_id, :postal_code, :address, :name, :shopping_cost, :total_payment, :payment_method, :status)
    params.require(:order).permit(:status)
  end
end

DemoWebSite/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?




  protected

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_items_path
    when Customer
      customer_path(resource)
    end
  end

  def after_sign_out_path_for(resource)
    case resource
    when :admin
      new_admin_session_path
      #'/admins/sign_in'
    when :customer
      root_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_out, keys: [:email])
  end

  def configure_permitted_parameters
    if resource_class == Customer
      devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :kana_last_name, :kana_first_name, :postal_code, :address, :telephone, :id_deleted])
    end
  end

end

DemoWebSite/app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

DemoWebSite/app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

DemoWebSite/app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

DemoWebSite/app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

DemoWebSite/app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

DemoWebSite/app/helpers/application_helper.rb
module ApplicationHelper

  def tax_price(item_price)
    price = (item_price * 1.10).round(0)
    return price
  end

  def subtotal_price(item_price, number)
    subtotal = (item_price * number * 1.10).round(0)
    return subtotal
  end

  def total_price_no_shipping(item)
    tmp = []
    item.each do |cart_item|
      tmp << cart_item.item.price * cart_item.amount * 1.10
    end
    @total_payment = tmp.sum.round(0) + @shipping_cost
    return tmp.sum.round(0)
  end
  
  def admin_total_price_no_shipping(item)
      tmp = []
      item.each do |order_detail|
        tmp << order_detail.price * order_detail.amount * 1.10
      end
      return tmp.sum.round(0)
  end


end

DemoWebSite/app/helpers/cart_items_helper.rb
module CartItemsHelper
end

DemoWebSite/app/helpers/customers_helper.rb
module CustomersHelper
end

DemoWebSite/app/helpers/homes_helper.rb
module HomesHelper
end

DemoWebSite/app/helpers/items_helper.rb
module ItemsHelper
end

DemoWebSite/app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

DemoWebSite/app/helpers/orders_helper.rb
module OrdersHelper
end

DemoWebSite/app/helpers/send_addresses_helper.rb
module SendAddressesHelper
end

DemoWebSite/app/views/admin/orders/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3 offset-md-1'>
      <nav class="navbar navbar-light">
      <h2>Order List</h2>
      </nav>
    </div>
  </div>

  <div class='row'>
    <table class='table'>
      <thead class='title bodydesign'>
        <tr>
          <th class='text-white bg-dark'>Purchase Date</th>
          <th class='text-white bg-dark'>Customer</th>
          <th class='text-white bg-dark'>Amount</th>
          <th class='text-white bg-dark'>Order_status</th>
        </tr>
      </thead>
      <tbody class='title bodydesign'>
        <% @orders.each do |order| %>
          <tr>
            <th><%= link_to order.created_at.to_s(:datetime_jp), admin_order_path(order), data: {"turbolinks" => false}, :style => 'color:black;' %></th>
            <th><%= order.name %></th>
            <th><%= order.total_payment %></th>
            <th><%= order.status %></th>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class='row'>
    <div class='mx-auto'>
      <p><%= paginate @orders %></p>
    </div>
  </div>
</div>

DemoWebSite/app/views/admin/orders/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='md-col-4'>
      <h2>Order Detail</h3>
    </div>
  </div>

  <div class='row'>
    <div class='md-col-2'>
      <table class='table table-borderless'>
        <body>
          <tr>
            <th>Name</th>
            <th><%= link_to @order.name, admin_customer_path(@order.customer_id), :style => 'color:black' %></th>
          </tr>
          <tr>
            <th>Purchase Date</th>
            <th><%= @order.created_at.to_s(:datetime_jp) %></th>
          </tr>
          <tr>
            <th>Send Address</th>
            <th><%= @order.address %></th>
          </tr>
          <tr>
            <th>Payment Method</th>
            <th><%= @order.payment_method %></th>
          </tr>
          <tr>
            <th>Order Status</th>
            <%= form_with model:@order, url: admin_order_path(@order.id), local:true, method: :patch do |f| %>
              <th>
                <%= f.select :status, Order.statuses.keys, {default: @order.status}, class:'btn btn-outline-dark' %>
              </th>
              <th>
                <%= f.submit 'Update', class:'btn btn-dark' %>
              </th>
            <% end %>
          </tr>
        </body>
      </table>
    </div>
  </div>
</div>

<div class='container'>
  <div class='row'>
    <div class='col-md-10 offset-md-1'>
      <table class='table'>
        <thead>
          <tr>
            <th class='text-white bg-dark'>Item</th>
            <th class='text-white bg-dark'>Cost(in_tax)</th>
            <th class='text-white bg-dark'>Amount</th>
            <th class='text-white bg-dark'>Subtotal</th>
            <th class='text-white bg-dark'>Making Status</th>
            <th class='bg-dark'></th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
            <tr>
              <th><%= order_detail.item.name %> </th>
              <th><%= tax_price(order_detail.item.price) %></th>
              <th><%= order_detail.amount %></th>
              <th><%= subtotal_price(order_detail.item.price, order_detail.amount) %></th>
              <%= form_with model:order_detail, url: admin_order_detail_path(order_detail), method: :patch, local:true do |f| %>
                <th><%= f.select :making_status, OrderDetail.making_statuses.keys, {default: order_detail.making_status}, class:'btn btn-outline-dark' %></th>
                <th>
                  <%= f.submit 'Update', class:'btn btn-dark' %>
                </th>
              <% end %>
            </tr>
          <% end %>
        </body>
      </table>
    </div>
  </div>
  <div class='row'>
    <div class='col-5 offset-1'>
      <table class='table table-borderless'>
        <tbody>
          <tr>
            <th>Item Total</th>
            <th>
              <%= admin_total_price_no_shipping(@order_details) %><text> yen</text>
            </th>
          </tr>
          <tr>
            <th>Shipping</th></th>
            <th>
              <%= @order.shipping_cost %><text> yen</text>
            </th>
          </tr>
          <tr>
            <th>Billed Amount</th>
            <th>
              <%= @order.total_payment %><text> yen</text>
            </th>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

</div>