DemoWebSite/config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'homes#top'
  get 'home/about' => 'homes#about'
  get 'home/thanks' => 'homes#thanks'

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :update, :edit, :create, :destroy]
    resources :items, only: [:index, :new, :show, :edit, :update, :destroy, :create]
    resources :orders, only: [:index, :show, :update, :edit]
    resources :order_details, only: [:show, :update]
  end

  scope module: :public do
    resources :customers, only: [:index, :show, :edit, :update, :create]
    resources :items, only: [:index, :show]
    resources :orders, only: [:index, :show, :new, :create, :update, :destroy] do
      collection do
        post 'confirm'
        get 'confirm'
      end
    end
    resources :order_details, only: [:show]
    resources :cart_items, only: [:index, :show, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :send_addresses, only: [:index, :edit, :destroy, :create, :update]
  end


end

DemoWebSite/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

DemoWebSite/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

DemoWebSite/app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
end

DemoWebSite/app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :send_addresses, dependent: :destroy
end

DemoWebSite/app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

DemoWebSite/app/models/item.rb
class Item < ApplicationRecord
    has_many :cart_items, dependent: :destroy
    has_many :order_details, dependent: :destroy
    belongs_to :genre
    attachment :image
end

DemoWebSite/app/models/order.rb
class Order < ApplicationRecord
    has_many :order_details, dependent: :destroy
    belongs_to :customer

    attr_accessor :address_option
    attr_accessor :other_send_address

    enum payment_method: {
        'credit_card':0, 'bank_transfer':1
    }

    enum status: {
        '入金待ち':0, '入金確認':1, '製作中':2, '発送準備中':3, '発送済み':4
    }
end

DemoWebSite/app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
    
    enum making_status: {
        '着手不可':0, '製作待ち':1, '製作中':2, '製作完了':3
    }
end

DemoWebSite/app/models/send_address.rb
class SendAddress < ApplicationRecord
    belongs_to :customer
end

DemoWebSite/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?




  protected

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_items_path
    when Customer
      customer_path(resource)
    end
  end

  def after_sign_out_path_for(resource)
    case resource
    when :admin
      new_admin_session_path
      #'/admins/sign_in'
    when :customer
      root_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_out, keys: [:email])
  end

  def configure_permitted_parameters
    if resource_class == Customer
      devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :kana_last_name, :kana_first_name, :postal_code, :address, :telephone, :id_deleted])
    end
  end

end

DemoWebSite/app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

DemoWebSite/app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

DemoWebSite/app/helpers/application_helper.rb
module ApplicationHelper

  def tax_price(item_price)
    price = (item_price * 1.10).round(0)
    return price
  end

  def subtotal_price(item_price, number)
    subtotal = (item_price * number * 1.10).round(0)
    return subtotal
  end

  def total_price_no_shipping(item)
    tmp = []
    item.each do |cart_item|
      tmp << cart_item.item.price * cart_item.amount * 1.10
    end
    @total_payment = tmp.sum.round(0) + @shipping_cost
    return tmp.sum.round(0)
  end
  
  def admin_total_price_no_shipping(item)
      tmp = []
      item.each do |order_detail|
        tmp << order_detail.price * order_detail.amount * 1.10
      end
      return tmp.sum.round(0)
  end


end

DemoWebSite/app/helpers/cart_items_helper.rb
module CartItemsHelper
end

DemoWebSite/app/helpers/customers_helper.rb
module CustomersHelper
end

DemoWebSite/app/helpers/homes_helper.rb
module HomesHelper
end

DemoWebSite/app/helpers/items_helper.rb
module ItemsHelper
end

DemoWebSite/app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

DemoWebSite/app/helpers/orders_helper.rb
module OrdersHelper
end

DemoWebSite/app/helpers/send_addresses_helper.rb
module SendAddressesHelper
end

DemoWebSite/app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

DemoWebSite/app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

DemoWebSite/app/views/layouts/_flash.html.erb
<% flash.each do |value| %>
    <p class="alert">
      <%= value %>
    </p>
<% end %>

DemoWebSite/app/views/layouts/_header.html.erb
<nav class='navbar navbar-expand-lg p-0 navbar-dark bg-dark'>
  <div class='container-fluid'>
    <div class='row mx-auto'>
      <p class='navbar-brand'><%= link_to 'Art Descovery', root_path, class:'text-light underline', :style => 'text-decoration:none;' %></p>
    </div>
  </div>
</nav>
<nav class='navbar navbar-expand-lg navbar-dark bg-dark'>
  <div class='container'>
    <div class='row mx-auto'>
      <div class='navbar-collapse collapse show'>
        <ul class='navbar-nav center' id='navi'>
        <% if customer_signed_in? %>
          <li class='fas nav-link navitem'><%= link_to 'Home', root_path, class:'text-light underline',:style => 'text-decoration:none;' %></li>
          <li class='fas nav-link navitem'><%= link_to 'Painting', items_path, class:'text-light underline', :style => 'text-decoration:none;' %></li>
          <li class='fas nav-link navitem'><%= link_to 'About', home_about_path, class:'text-light underline', :style => 'text-decoration:none;' %></li>
          <li class='fas nav-link navitem'><%= link_to 'Shopping', cart_item_path(current_customer), class:'text-light underline', :style => 'text-decoration:none;' %></li>
          <li class='fas nav-link navitem'><%= link_to '', customer_path(current_customer), class:'text-light fas fa-user underline', :style => 'text-decoration:none;' %></li>
        <% elsif admin_signed_in? %>
          <li class='fas nav-link navitem'><%= link_to 'Customer', admin_customers_path, class:'text-light underline',:style => 'text-decoration:none;' %></li>
          <li class='fas nav-link navitem'><%= link_to 'Painting', admin_items_path, class:'text-light underline', :style => 'text-decoration:none;' %></li>
          <li class='fas nav-link navitem'><%= link_to 'Genre', admin_genres_path, class:'text-light underline', :style => 'text-decoration:none;' %></li>
          <li class='fas nav-link navitem'><%= link_to 'Order', admin_orders_path, class:'text-light underline', :style => 'text-decoration:none;' %></li>
          <li class='fas nav-link navitem'><%= link_to 'Logout', destroy_admin_session_path, method: :delete, class:'text-light underline', :style => 'text-decoration:none;' %></li>
        <% else %>
          <li class='fas nav-link navitem'><%= link_to 'Home', root_path, class:'text-light underline',:style => 'text-decoration:none;' %></li>
          <li class='fas nav-link navitem'><%= link_to 'Painting', items_path, class:'text-light underline', :style => 'text-decoration:none;' %></li>
          <li class='fas nav-link navitem'><%= link_to 'About', home_about_path, class:'text-light underline', :style => 'text-decoration:none;' %></li>
          <li class='fas nav-link navitem'><%= link_to 'Shopping', cart_items_path, class:'text-light underline', :style => 'text-decoration:none;' %></li>
          <li class='fas nav-link navitem'><a class='text-light fas fa-user underline naveffect' href='#'></a>
            <ul>
              <li class='fas nav-link' href='#'><%= link_to 'Registration', new_customer_registration_path, class:'text-light underline', :style => 'text-decoration:none;' %></li>
              <li class='fas nav-link' href='#'><%= link_to 'Login', new_customer_session_path, class:'text-light underline', :style => 'text-decoration:none;' %></li>
            </ul>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

DemoWebSite/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoWebSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel="stylesheet">
  </head>
  
  <header>
    <%= render 'layouts/header' %>
  </header>

  <body>
    <%= yield %>
  </body>
</html>