DemoWebSite/config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'homes#top'
  get 'home/about' => 'homes#about'
  get 'home/thanks' => 'homes#thanks'

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :update, :edit, :create, :destroy]
    resources :items, only: [:index, :new, :show, :edit, :update, :destroy, :create]
    resources :orders, only: [:index, :show, :update, :edit]
    resources :order_details, only: [:show, :update]
  end

  scope module: :public do
    resources :customers, only: [:index, :show, :edit, :update, :create]
    resources :items, only: [:index, :show]
    resources :orders, only: [:index, :show, :new, :create, :update, :destroy] do
      collection do
        post 'confirm'
        get 'confirm'
      end
    end
    resources :order_details, only: [:show]
    resources :cart_items, only: [:index, :show, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :send_addresses, only: [:index, :edit, :destroy, :create, :update]
  end


end

DemoWebSite/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

DemoWebSite/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

DemoWebSite/app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
end

DemoWebSite/app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :send_addresses, dependent: :destroy
end

DemoWebSite/app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

DemoWebSite/app/models/item.rb
class Item < ApplicationRecord
    has_many :cart_items, dependent: :destroy
    has_many :order_details, dependent: :destroy
    belongs_to :genre
    attachment :image
end

DemoWebSite/app/models/order.rb
class Order < ApplicationRecord
    has_many :order_details, dependent: :destroy
    belongs_to :customer

    attr_accessor :address_option
    attr_accessor :other_send_address

    enum payment_method: {
        'credit_card':0, 'bank_transfer':1
    }

    enum status: {
        '入金待ち':0, '入金確認':1, '製作中':2, '発送準備中':3, '発送済み':4
    }
end

DemoWebSite/app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
    
    enum making_status: {
        '着手不可':0, '製作待ち':1, '製作中':2, '製作完了':3
    }
end

DemoWebSite/app/models/send_address.rb
class SendAddress < ApplicationRecord
    belongs_to :customer
end

DemoWebSite/app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page]).per(8)
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_items_path
    else
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_items_path
    else
      render :edit
    end

  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

DemoWebSite/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?




  protected

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_items_path
    when Customer
      customer_path(resource)
    end
  end

  def after_sign_out_path_for(resource)
    case resource
    when :admin
      new_admin_session_path
      #'/admins/sign_in'
    when :customer
      root_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_out, keys: [:email])
  end

  def configure_permitted_parameters
    if resource_class == Customer
      devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :kana_last_name, :kana_first_name, :postal_code, :address, :telephone, :id_deleted])
    end
  end

end

DemoWebSite/app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

DemoWebSite/app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

DemoWebSite/app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

DemoWebSite/app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

DemoWebSite/app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

DemoWebSite/app/helpers/application_helper.rb
module ApplicationHelper

  def tax_price(item_price)
    price = (item_price * 1.10).round(0)
    return price
  end

  def subtotal_price(item_price, number)
    subtotal = (item_price * number * 1.10).round(0)
    return subtotal
  end

  def total_price_no_shipping(item)
    tmp = []
    item.each do |cart_item|
      tmp << cart_item.item.price * cart_item.amount * 1.10
    end
    @total_payment = tmp.sum.round(0) + @shipping_cost
    return tmp.sum.round(0)
  end
  
  def admin_total_price_no_shipping(item)
      tmp = []
      item.each do |order_detail|
        tmp << order_detail.price * order_detail.amount * 1.10
      end
      return tmp.sum.round(0)
  end


end

DemoWebSite/app/helpers/cart_items_helper.rb
module CartItemsHelper
end

DemoWebSite/app/helpers/customers_helper.rb
module CustomersHelper
end

DemoWebSite/app/helpers/homes_helper.rb
module HomesHelper
end

DemoWebSite/app/helpers/items_helper.rb
module ItemsHelper
end

DemoWebSite/app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

DemoWebSite/app/helpers/orders_helper.rb
module OrdersHelper
end

DemoWebSite/app/helpers/send_addresses_helper.rb
module SendAddressesHelper
end

DemoWebSite/app/views/admin/items/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-4 offset-1'>
      <nav class="navbar navbar-light">
      <h2>Editing Item</h2>
      </nav>
    </div>
    <div class='col-md-8'></div>
  </div>
  <div class='row center'>
    <div class='mx-auto newitem'>
      <%= form_with model:@item, url: admin_item_path(@item), local:true do |f| %>
        <div class='form-group'>
          <label for='inputImage'>Image</label><br>
          <%= f.attachment_field :image, id:'inputImage', placeholder:'写真' %>
        </div>
        <div class='form-group'>
          <label for='inputName'>Name</label><br>
          <%= f.text_field :name, autofocus: true, id:'inputName', placeholder:'名前' %>
        </div>
        <div class='form-group'>
          <label for='inputIntroduction'>Introduction</label><br>
          <%= f.text_field :introduction, autofocus: true, id:'inputIntroduction', placeholder:'ここに説明文を記述します', :size=>'30x5' %>
        </div>
        <div class='form-group'>
          <label for='inputGenre'>Genre</label><br>
          <%= f.collection_select :genre_id, Genre.all, :id, :name,{}, {class: 'btn btn-outline-dark'}%>
        </div>
        <div class='form-group'>
          <label for='inputPrice'>Price(no_tax)</label><br>
          <%= f.number_field :price, autofocus: true, id:'inputPrice', placeholder:'税抜価格' %>
          <text>円</text>
        </div>
        <div class='form-group'>
          <label>Status</label><br>
          <%= f.radio_button :is_active, :true %>
          <%= f.label :is_active, '販売中', {value: :true, style: 'display: inline-block;'} %>
          <%= f.radio_button :is_active, :false %>
          <%= f.label :is_active, '販売停止中', {value: :false, style: 'display: inline-block;'} %>
        </div>
        <div class='form-group center'>
          <%= f.submit 'Save', class:'btn btn-outline-dark' %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

DemoWebSite/app/views/admin/items/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3 offset-md-1'>
      <nav class="navbar navbar-light" >
       <h2>Items</h2>
      </nav>
    </div>
    <div class='col-3 offset-5'>
      <%= link_to new_admin_item_path, class:"btn btn-outline-dark rounded-circle p-0 button_text", :style => "width:3rem;height:3rem;" do %>
      <text class='button_text'>+</text>
      <% end %>
    </div>
  </div>
  <%= render partial: 'layouts/flash' %>
  <div class='row center'>
   <div class="col-8 offset-1">
    <table class='table'>
      <thead class="thead-light bodydesign">
        <tr>
          <th class='text-white bg-dark'>ID</th>
          <th class='text-white bg-dark'>Name</th>
          <th class='text-white bg-dark'>Price(no_tax)</th>
          <th class='text-white bg-dark'>Genre</th>
          <th class='text-white bg-dark'>Status</th>
        </tr>
      </thead>
      <tbody class='title bodydesign'>
        <% @items.each do |item| %>
          <tr>
            <th><%= item.id %></th>
            <th><%= link_to item.name, admin_item_path(item.id), :style => 'color:black;' %></th>
            <th class='textalign'><%= item.price %></th>
            <th><%= item.genre.name %></th>
            <% if item.is_active == true %>
              <th class='text-success'>販売中</th>
            <% else %>
              <th class='text-secondary'>売切れ</th>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
   </div>
  </div>
  <div class='row'>
      <div class='mx-auto pagination-design'>
        <p><%= paginate @items %></p>
      </div>
  </div>
</div>

DemoWebSite/app/views/admin/items/new.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-4'>
      <h2>New Item</h2>
    </div>
    <div class='col-md-8'></div>
  </div>
  <div class='row'>
    <div class='mx-auto newitem'>
        <%= render partial: 'layouts/flash' %>
      <%= form_with model:@item, url: admin_items_path, local:true do |f| %>
        <div class='form-group'>
          <label for='inputImage'>Image</label><br>
          <%= f.attachment_field :image, placeholder:'写真' %>
        </div>
        <div class='form-group title'>
          <label for='inputName'>Name</label><br>
          <%= f.text_field :name, autofocus: true, id:'inputName' %>
        </div>
        <div class='form-group'>
          <label for='inputIntroduction'>Introduction</label><br>
          <%= f.text_field :introduction, autofocus: true, id:'inputIntroduction' %>
        </div>
        <div class='form-group'>
          <label for='inputGenre'>Genre</label><br>
          <%= f.collection_select :genre_id, Genre.all, :id, :name, {include_blank: "Select"}, {class: 'btn btn-outline-dark'} %>
        </div>
        <div class='form-group'>
          <label for='inputPrice'>Price(no_tax)</label><br>
          <%= f.number_field :price, autofocus: true, id:'inputPrice', placeholder:'税抜価格' %>
          <text>yen</text>
        </div>
        <div class='form-group'>
          <label>Status</label><br>
          <%= f.radio_button :is_active, :true %>
          <%= f.label :is_active, '販売中', {value: :true, style: 'display: inline-block;'} %>
          <%= f.radio_button :is_active, :false %>
          <%= f.label :is_active, '販売停止中', {value: :false, style: 'display: inline-block;'} %>
        </div>
        <div class='form-group center'>
          <%= f.submit 'Submit', class:'btn btn-lg btn-outline-dark' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

DemoWebSite/app/views/admin/items/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <nav class="navbar navbar-light">
        <h2>Details</h2>
      </nav>
    </div>
  </div>
    <%= render partial: 'layouts/flash' %>
  <div class='row'>
    <div class='col-md-3'>
      <%= attachment_image_tag @item, :image, :fill, 300, 200, format:'jpeg', fallback:'no_image.jpg' %>
    </div>

    <div class='col-4 offset-1'>
      <table class='table table-borderless'>
        <tr>
          <th>Name</th>
          <th><%= @item.name %></th>
        </tr>
        <tr>
          <th>Introduction</th>
          <th><%= @item.introduction %></th>
        </tr>
        <tr>
          <th>Genre</th>
          <th><%= @item.genre.name %></th>
        </tr>
        <tr>
          <th>Price(in_tax)<br>(no_tax）</th>

          <th><%= (@item.price*1.10).round %>(<%= @item.price %>)<text>yen</text></th>
        </tr>
        <tr>
          <th>Status</th>
          <% if @item.is_active == true %>
            <th class='text-success'>販売中</th>
          <% else %>
            <th class='text-secondary'>販売停止中</th>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
  <div class='row'>
    <div class='mx-auto'>
      <%= link_to 'Edit', edit_admin_item_path(@item.id), class:'btn btn-lg btn-dark' %>
    </div>
  </div>
</div>